name: deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  checks: write
  pull-requests: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - uses: actions/checkout@v3
      - name: make application.yml
        run: |
          # mkdir src/main/resources
          mkdir -p ./src/main/resources
          
          # create application.yml
          cd ./src/main/resources
          
          # application.yml 파일 생성
          touch ./application.yml
          
          # GitHub-Actions 에서 설정한 값을 application.yml 파일에 쓰기
          echo "${{ secrets.APPLICATION }}" >> ./application.yml

        shell: bash

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew bootJar
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/rb_backend .
          docker push ${{ secrets.DOCKER_REPO }}/rb_backend
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            sudo docker pull ${{ secrets.DOCKER_REPO }}/rb_backend
            sudo docker compose -f docker-compose-app.yml down
            sudo docker compose -f docker-compose-app.yml up -d